%% DistOp
%  A class of functions for time recording in critical parts.
%
%% Contribution
%  Author : Jia-Wei Lin (jiaweilin@nycu.edu.tw)
%  Created: 2023/05/04
% 
%  Copyright Jia-Wei Lin
%  https://sites.google.com/g2.nctu.edu.tw/jwlin
classdef EventTime 
    properties
        data = [];
    end
    methods(Static)
        function obj = Psi(type)
            if strcmp(type,'t') == 1
                obj = struct(   'D', 0,...
                              'rs1', 0,...
                              'rs2', 0,...
                              'rs3', 0,...
                               'P1', 0,...
                               'P2', 0,...
                               'P3', 0,...
                             'fft1', 0,...
                             'fft2', 0,...
                             'fft3', 0,...
                               'R1', 0,...
                               'R2', 0,...
                               'R3', 0,...
                              'cat', 0,...
                                'S', 0     );
            elseif strcmp(type,'nt') == 1
                obj = struct(   'D', 0,...
                              'rs1', 0,...
                              'rs2', 0,...
                              'rs3', 0,...
                               'P1', 0,...
                               'P2', 0,...
                               'P3', 0,...
                            'ifft1', 0,...
                            'ifft2', 0,...
                            'ifft3', 0,...
                               'R1', 0,...
                               'R2', 0,...
                               'R3', 0,...
                              'cat', 0,...
                                'S', 0     );
            end
        end

        function obj = Phi(type)
            if strcmp(type,'t') == 1
                obj = struct(   'D', 0,...
                              'rs1', 0,...
                              'rs2', 0,...
                              'rs3', 0,...
                               'P1', 0,...
                               'P2', 0,...
                               'P3', 0,...
                             'fft1', 0,...
                             'fft2', 0,...
                             'fft3', 0,...
                               'R1', 0,...
                               'R2', 0,...
                               'R3', 0,...
                              'cat', 0,...
                                'S', 0     );
            elseif strcmp(type,'nt') == 1
                obj = struct(   'D', 0,...
                              'rs1', 0,...
                              'rs2', 0,...
                              'rs3', 0,...
                               'P1', 0,...
                               'P2', 0,...
                               'P3', 0,...
                            'ifft1', 0,...
                            'ifft2', 0,...
                            'ifft3', 0,...
                               'R1', 0,...
                               'R2', 0,...
                               'R3', 0,...
                              'cat', 0,...
                                'S', 0     );
            end
        end

        function obj = pcg(type)
            if strcmp(type,'N')
                obj = struct('iter',[],...
                             'time',[],...
                             'Phis',EventTime.Phi('t'), ...
                              'Phi',EventTime.Phi('nt')     );
            elseif strcmp(type,'M')
                obj = struct('iter',[],...
                             'time',[],...
                             'Psis',EventTime.Psi('t'), ...
                              'Psi',EventTime.Psi('nt')     );
            end
        end
    end
end