function [ mtx_A, mtx_B ] = Convert2gpuarray(mtx_A,mtx_B)
    covert_list = {'mtx_A.D.Phi',...
                   'mtx_A.D.Psi',...
                   'mtx_A.S.Phi',...
                   'mtx_A.S.Psi',...
                   'mtx_A.P_idx.Psi_1',...
                   'mtx_A.P_idx.Psi_2',...
                   'mtx_A.P_idx.Psi_3',...
                   'mtx_A.P_idx.Phi_1',...
                   'mtx_A.P_idx.Phi_2',...
                   'mtx_A.P_idx.Phi_3',...
                   'mtx_A.Pi.Pr',...
                   'mtx_A.Pi.Qr',...
                   'mtx_A.Lambda_curl.Sigma.r',...
                   'mtx_B.N_int',...
                   'mtx_B.M_int',...
                   'mtx_B.J_int'};
    for i = 1:length(covert_list)
        eval([covert_list{i},' = gpuArray(',covert_list{i},');']);
    end
end